const p1_name_rep = nodecg.Replicant('p1_name', 'gg-gcf-overlay');
const p1_record_rep = nodecg.Replicant('p1_record', 'gg-gcf-overlay');
const p1_wins_rep = nodecg.Replicant('p1_wins', 'gg-gcf-overlay');
const round_rep = nodecg.Replicant('round', 'gg-gcf-overlay');
const p2_name_rep = nodecg.Replicant('p2_name', 'gg-gcf-overlay');
const p2_record_rep = nodecg.Replicant('p2_record', 'gg-gcf-overlay');
const p2_wins_rep = nodecg.Replicant('p2_wins', 'gg-gcf-overlay');

p1_name_rep.on('change', (newValue, oldValue) => {	
	p1_name.innerText = `${newValue}` ;
});	
p1_record_rep.on('change', (newValue, oldValue) => {	
	p1_record.innerText = `${newValue}` ;
});	
p1_wins_rep.on('change', (newValue, oldValue) => {	
	if (p1_wins_rep.value == 0){
        document.getElementById("p1_wins").classList.add("score0");
        document.getElementById("p1_wins").classList.remove("score1");
        document.getElementById("p1_wins").classList.remove("score2");
    } else if (p1_wins_rep.value == 1 ){
        document.getElementById("p1_wins").classList.remove("score0");
        document.getElementById("p1_wins").classList.add("score1");
        document.getElementById("p1_wins").classList.remove("score2");
    } else if (p1_wins_rep.value == 2) {
        document.getElementById("p1_wins").classList.remove("score0");
        document.getElementById("p1_wins").classList.remove("score1");
        document.getElementById("p1_wins").classList.add("score2");
    } else {
        document.getElementById("p1_wins").classList.remove("score0");
        document.getElementById("p1_wins").classList.remove("score1");
        document.getElementById("p1_wins").classList.add("score2");
    }
});	
round_rep.on('change', (newValue, oldValue) => {	
	if (round_rep.value == "Round 1"){
        document.getElementById("t_round").classList.add("round1");
        document.getElementById("t_round").classList.remove("round2");
        document.getElementById("t_round").classList.remove("round3");
        document.getElementById("t_round").classList.remove("round4");
        document.getElementById("t_round").classList.remove("round5");
        document.getElementById("t_round").classList.remove("round6");
        document.getElementById("t_round").classList.remove("round7");
        document.getElementById("t_round").classList.remove("round8");
        document.getElementById("t_round").classList.remove("round9");
        document.getElementById("t_round").classList.remove("round10");
        document.getElementById("t_round").classList.remove("round11");
        document.getElementById("t_round").classList.remove("round12");
        document.getElementById("t_round").classList.remove("round13");
        document.getElementById("t_round").classList.remove("round14");
        document.getElementById("t_round").classList.remove("round32");
        document.getElementById("t_round").classList.remove("round16");
        document.getElementById("t_round").classList.remove("roundqf");
        document.getElementById("t_round").classList.remove("roundsf");
        document.getElementById("t_round").classList.remove("roundgf");
    } else if (round_rep.value == "Round 2" ){
        document.getElementById("t_round").classList.remove("round1");
        document.getElementById("t_round").classList.add("round2");
        document.getElementById("t_round").classList.remove("round3");
        document.getElementById("t_round").classList.remove("round4");
        document.getElementById("t_round").classList.remove("round5");
        document.getElementById("t_round").classList.remove("round6");
        document.getElementById("t_round").classList.remove("round7");
        document.getElementById("t_round").classList.remove("round8");
        document.getElementById("t_round").classList.remove("round9");
        document.getElementById("t_round").classList.remove("round10");
        document.getElementById("t_round").classList.remove("round11");
        document.getElementById("t_round").classList.remove("round12");
        document.getElementById("t_round").classList.remove("round13");
        document.getElementById("t_round").classList.remove("round14");
        document.getElementById("t_round").classList.remove("round32");
        document.getElementById("t_round").classList.remove("round16");
        document.getElementById("t_round").classList.remove("roundqf");
        document.getElementById("t_round").classList.remove("roundsf");
        document.getElementById("t_round").classList.remove("roundgf");
    } else if (round_rep.value == "Round 3" ){
        document.getElementById("t_round").classList.remove("round1");
        document.getElementById("t_round").classList.remove("round2");
        document.getElementById("t_round").classList.add("round3");
        document.getElementById("t_round").classList.remove("round4");
        document.getElementById("t_round").classList.remove("round5");
        document.getElementById("t_round").classList.remove("round6");
        document.getElementById("t_round").classList.remove("round7");
        document.getElementById("t_round").classList.remove("round8");
        document.getElementById("t_round").classList.remove("round9");
        document.getElementById("t_round").classList.remove("round10");
        document.getElementById("t_round").classList.remove("round11");
        document.getElementById("t_round").classList.remove("round12");
        document.getElementById("t_round").classList.remove("round13");
        document.getElementById("t_round").classList.remove("round14");
        document.getElementById("t_round").classList.remove("round32");
        document.getElementById("t_round").classList.remove("round16");
        document.getElementById("t_round").classList.remove("roundqf");
        document.getElementById("t_round").classList.remove("roundsf");
        document.getElementById("t_round").classList.remove("roundgf");
    } else if (round_rep.value == "Round 4" ){
        document.getElementById("t_round").classList.remove("round1");
        document.getElementById("t_round").classList.remove("round2");
        document.getElementById("t_round").classList.remove("round3");
        document.getElementById("t_round").classList.add("round4");
        document.getElementById("t_round").classList.remove("round5");
        document.getElementById("t_round").classList.remove("round6");
        document.getElementById("t_round").classList.remove("round7");
        document.getElementById("t_round").classList.remove("round8");
        document.getElementById("t_round").classList.remove("round9");
        document.getElementById("t_round").classList.remove("round10");
        document.getElementById("t_round").classList.remove("round11");
        document.getElementById("t_round").classList.remove("round12");
        document.getElementById("t_round").classList.remove("round13");
        document.getElementById("t_round").classList.remove("round14");
        document.getElementById("t_round").classList.remove("round32");
        document.getElementById("t_round").classList.remove("round16");
        document.getElementById("t_round").classList.remove("roundqf");
        document.getElementById("t_round").classList.remove("roundsf");
        document.getElementById("t_round").classList.remove("roundgf");
    } else if (round_rep.value == "Round 5" ){
        document.getElementById("t_round").classList.remove("round1");
        document.getElementById("t_round").classList.remove("round2");
        document.getElementById("t_round").classList.remove("round3");
        document.getElementById("t_round").classList.remove("round4");
        document.getElementById("t_round").classList.add("round5");
        document.getElementById("t_round").classList.remove("round6");
        document.getElementById("t_round").classList.remove("round7");
        document.getElementById("t_round").classList.remove("round8");
        document.getElementById("t_round").classList.remove("round9");
        document.getElementById("t_round").classList.remove("round10");
        document.getElementById("t_round").classList.remove("round11");
        document.getElementById("t_round").classList.remove("round12");
        document.getElementById("t_round").classList.remove("round13");
        document.getElementById("t_round").classList.remove("round14");
        document.getElementById("t_round").classList.remove("round32");
        document.getElementById("t_round").classList.remove("round16");
        document.getElementById("t_round").classList.remove("roundqf");
        document.getElementById("t_round").classList.remove("roundsf");
        document.getElementById("t_round").classList.remove("roundgf");
    } else if (round_rep.value == "Round 6" ){
        document.getElementById("t_round").classList.remove("round1");
        document.getElementById("t_round").classList.remove("round2");
        document.getElementById("t_round").classList.remove("round3");
        document.getElementById("t_round").classList.remove("round4");
        document.getElementById("t_round").classList.remove("round5");
        document.getElementById("t_round").classList.add("round6");
        document.getElementById("t_round").classList.remove("round7");
        document.getElementById("t_round").classList.remove("round8");
        document.getElementById("t_round").classList.remove("round9");
        document.getElementById("t_round").classList.remove("round10");
        document.getElementById("t_round").classList.remove("round11");
        document.getElementById("t_round").classList.remove("round12");
        document.getElementById("t_round").classList.remove("round13");
        document.getElementById("t_round").classList.remove("round14");
        document.getElementById("t_round").classList.remove("round32");
        document.getElementById("t_round").classList.remove("round16");
        document.getElementById("t_round").classList.remove("roundqf");
        document.getElementById("t_round").classList.remove("roundsf");
        document.getElementById("t_round").classList.remove("roundgf");
    } else if (round_rep.value == "Round 7" ){
        document.getElementById("t_round").classList.remove("round1");
        document.getElementById("t_round").classList.remove("round2");
        document.getElementById("t_round").classList.remove("round3");
        document.getElementById("t_round").classList.remove("round4");
        document.getElementById("t_round").classList.remove("round5");
        document.getElementById("t_round").classList.remove("round6");
        document.getElementById("t_round").classList.add("round7");
        document.getElementById("t_round").classList.remove("round8");
        document.getElementById("t_round").classList.remove("round9");
        document.getElementById("t_round").classList.remove("round10");
        document.getElementById("t_round").classList.remove("round11");
        document.getElementById("t_round").classList.remove("round12");
        document.getElementById("t_round").classList.remove("round13");
        document.getElementById("t_round").classList.remove("round14");
        document.getElementById("t_round").classList.remove("round32");
        document.getElementById("t_round").classList.remove("round16");
        document.getElementById("t_round").classList.remove("roundqf");
        document.getElementById("t_round").classList.remove("roundsf");
        document.getElementById("t_round").classList.remove("roundgf");
    } else if (round_rep.value == "Round 8" ){
        document.getElementById("t_round").classList.remove("round1");
        document.getElementById("t_round").classList.remove("round2");
        document.getElementById("t_round").classList.remove("round3");
        document.getElementById("t_round").classList.remove("round4");
        document.getElementById("t_round").classList.remove("round5");
        document.getElementById("t_round").classList.remove("round6");
        document.getElementById("t_round").classList.remove("round7");
        document.getElementById("t_round").classList.add("round8");
        document.getElementById("t_round").classList.remove("round9");
        document.getElementById("t_round").classList.remove("round10");
        document.getElementById("t_round").classList.remove("round11");
        document.getElementById("t_round").classList.remove("round12");
        document.getElementById("t_round").classList.remove("round13");
        document.getElementById("t_round").classList.remove("round14");
        document.getElementById("t_round").classList.remove("round32");
        document.getElementById("t_round").classList.remove("round16");
        document.getElementById("t_round").classList.remove("roundqf");
        document.getElementById("t_round").classList.remove("roundsf");
        document.getElementById("t_round").classList.remove("roundgf");
    } else if (round_rep.value == "Round 9" ){
        document.getElementById("t_round").classList.remove("round1");
        document.getElementById("t_round").classList.remove("round2");
        document.getElementById("t_round").classList.remove("round3");
        document.getElementById("t_round").classList.remove("round4");
        document.getElementById("t_round").classList.remove("round5");
        document.getElementById("t_round").classList.remove("round6");
        document.getElementById("t_round").classList.remove("round7");
        document.getElementById("t_round").classList.remove("round8");
        document.getElementById("t_round").classList.add("round9");
        document.getElementById("t_round").classList.remove("round10");
        document.getElementById("t_round").classList.remove("round11");
        document.getElementById("t_round").classList.remove("round12");
        document.getElementById("t_round").classList.remove("round13");
        document.getElementById("t_round").classList.remove("round14");
        document.getElementById("t_round").classList.remove("round32");
        document.getElementById("t_round").classList.remove("round16");
        document.getElementById("t_round").classList.remove("roundqf");
        document.getElementById("t_round").classList.remove("roundsf");
        document.getElementById("t_round").classList.remove("roundgf");
    } else if (round_rep.value == "Round 10" ){
        document.getElementById("t_round").classList.remove("round1");
        document.getElementById("t_round").classList.remove("round2");
        document.getElementById("t_round").classList.remove("round3");
        document.getElementById("t_round").classList.remove("round4");
        document.getElementById("t_round").classList.remove("round5");
        document.getElementById("t_round").classList.remove("round6");
        document.getElementById("t_round").classList.remove("round7");
        document.getElementById("t_round").classList.remove("round8");
        document.getElementById("t_round").classList.remove("round9");
        document.getElementById("t_round").classList.add("round10");
        document.getElementById("t_round").classList.remove("round11");
        document.getElementById("t_round").classList.remove("round12");
        document.getElementById("t_round").classList.remove("round13");
        document.getElementById("t_round").classList.remove("round14");
        document.getElementById("t_round").classList.remove("round32");
        document.getElementById("t_round").classList.remove("round16");
        document.getElementById("t_round").classList.remove("roundqf");
        document.getElementById("t_round").classList.remove("roundsf");
        document.getElementById("t_round").classList.remove("roundgf");
    } else if (round_rep.value == "Round 11" ){
        document.getElementById("t_round").classList.remove("round1");
        document.getElementById("t_round").classList.remove("round2");
        document.getElementById("t_round").classList.remove("round3");
        document.getElementById("t_round").classList.remove("round4");
        document.getElementById("t_round").classList.remove("round5");
        document.getElementById("t_round").classList.remove("round6");
        document.getElementById("t_round").classList.remove("round7");
        document.getElementById("t_round").classList.remove("round8");
        document.getElementById("t_round").classList.remove("round9");
        document.getElementById("t_round").classList.remove("round10");
        document.getElementById("t_round").classList.add("round11");
        document.getElementById("t_round").classList.remove("round12");
        document.getElementById("t_round").classList.remove("round13");
        document.getElementById("t_round").classList.remove("round14");
        document.getElementById("t_round").classList.remove("round32");
        document.getElementById("t_round").classList.remove("round16");
        document.getElementById("t_round").classList.remove("roundqf");
        document.getElementById("t_round").classList.remove("roundsf");
        document.getElementById("t_round").classList.remove("roundgf");
    } else if (round_rep.value == "Round 12" ){
        document.getElementById("t_round").classList.remove("round1");
        document.getElementById("t_round").classList.remove("round2");
        document.getElementById("t_round").classList.remove("round3");
        document.getElementById("t_round").classList.remove("round4");
        document.getElementById("t_round").classList.remove("round5");
        document.getElementById("t_round").classList.remove("round6");
        document.getElementById("t_round").classList.remove("round7");
        document.getElementById("t_round").classList.remove("round8");
        document.getElementById("t_round").classList.remove("round9");
        document.getElementById("t_round").classList.remove("round10");
        document.getElementById("t_round").classList.remove("round11");
        document.getElementById("t_round").classList.add("round12");
        document.getElementById("t_round").classList.remove("round13");
        document.getElementById("t_round").classList.remove("round14");
        document.getElementById("t_round").classList.remove("round32");
        document.getElementById("t_round").classList.remove("round16");
        document.getElementById("t_round").classList.remove("roundqf");
        document.getElementById("t_round").classList.remove("roundsf");
        document.getElementById("t_round").classList.remove("roundgf");
    } else if (round_rep.value == "Round 13" ){
        document.getElementById("t_round").classList.remove("round1");
        document.getElementById("t_round").classList.remove("round2");
        document.getElementById("t_round").classList.remove("round3");
        document.getElementById("t_round").classList.remove("round4");
        document.getElementById("t_round").classList.remove("round5");
        document.getElementById("t_round").classList.remove("round6");
        document.getElementById("t_round").classList.remove("round7");
        document.getElementById("t_round").classList.remove("round8");
        document.getElementById("t_round").classList.remove("round9");
        document.getElementById("t_round").classList.remove("round10");
        document.getElementById("t_round").classList.remove("round11");
        document.getElementById("t_round").classList.remove("round12");
        document.getElementById("t_round").classList.add("round13");
        document.getElementById("t_round").classList.remove("round14");
        document.getElementById("t_round").classList.remove("round32");
        document.getElementById("t_round").classList.remove("round16");
        document.getElementById("t_round").classList.remove("roundqf");
        document.getElementById("t_round").classList.remove("roundsf");
        document.getElementById("t_round").classList.remove("roundgf");
    } else if (round_rep.value == "Round 14" ){
        document.getElementById("t_round").classList.remove("round1");
        document.getElementById("t_round").classList.remove("round2");
        document.getElementById("t_round").classList.remove("round3");
        document.getElementById("t_round").classList.remove("round4");
        document.getElementById("t_round").classList.remove("round5");
        document.getElementById("t_round").classList.remove("round6");
        document.getElementById("t_round").classList.remove("round7");
        document.getElementById("t_round").classList.remove("round8");
        document.getElementById("t_round").classList.remove("round9");
        document.getElementById("t_round").classList.remove("round10");
        document.getElementById("t_round").classList.remove("round11");
        document.getElementById("t_round").classList.remove("round12");
        document.getElementById("t_round").classList.remove("round13");
        document.getElementById("t_round").classList.add("round14");
        document.getElementById("t_round").classList.remove("round32");
        document.getElementById("t_round").classList.remove("round16");
        document.getElementById("t_round").classList.remove("roundqf");
        document.getElementById("t_round").classList.remove("roundsf");
        document.getElementById("t_round").classList.remove("roundgf");
    } else if (round_rep.value == "Top 32" ){
        document.getElementById("t_round").classList.remove("round1");
        document.getElementById("t_round").classList.remove("round2");
        document.getElementById("t_round").classList.remove("round3");
        document.getElementById("t_round").classList.remove("round4");
        document.getElementById("t_round").classList.remove("round5");
        document.getElementById("t_round").classList.remove("round6");
        document.getElementById("t_round").classList.remove("round7");
        document.getElementById("t_round").classList.remove("round8");
        document.getElementById("t_round").classList.remove("round9");
        document.getElementById("t_round").classList.remove("round10");
        document.getElementById("t_round").classList.remove("round11");
        document.getElementById("t_round").classList.remove("round12");
        document.getElementById("t_round").classList.remove("round13");
        document.getElementById("t_round").classList.remove("round14");
        document.getElementById("t_round").classList.add("round32");
        document.getElementById("t_round").classList.remove("round16");
        document.getElementById("t_round").classList.remove("roundqf");
        document.getElementById("t_round").classList.remove("roundsf");
        document.getElementById("t_round").classList.remove("roundgf");
    } else if (round_rep.value == "Quarterfinals" ){
        document.getElementById("t_round").classList.remove("round1");
        document.getElementById("t_round").classList.remove("round2");
        document.getElementById("t_round").classList.remove("round3");
        document.getElementById("t_round").classList.remove("round4");
        document.getElementById("t_round").classList.remove("round5");
        document.getElementById("t_round").classList.remove("round6");
        document.getElementById("t_round").classList.remove("round7");
        document.getElementById("t_round").classList.remove("round8");
        document.getElementById("t_round").classList.remove("round9");
        document.getElementById("t_round").classList.remove("round10");
        document.getElementById("t_round").classList.remove("round11");
        document.getElementById("t_round").classList.remove("round12");
        document.getElementById("t_round").classList.remove("round13");
        document.getElementById("t_round").classList.remove("round14");
        document.getElementById("t_round").classList.remove("round32");
        document.getElementById("t_round").classList.remove("round16");
        document.getElementById("t_round").classList.add("roundqf");
        document.getElementById("t_round").classList.remove("roundsf");
        document.getElementById("t_round").classList.remove("roundgf");
    } else if (round_rep.value == "Semifinals" ){
        document.getElementById("t_round").classList.remove("round1");
        document.getElementById("t_round").classList.remove("round2");
        document.getElementById("t_round").classList.remove("round3");
        document.getElementById("t_round").classList.remove("round4");
        document.getElementById("t_round").classList.remove("round5");
        document.getElementById("t_round").classList.remove("round6");
        document.getElementById("t_round").classList.remove("round7");
        document.getElementById("t_round").classList.remove("round8");
        document.getElementById("t_round").classList.remove("round9");
        document.getElementById("t_round").classList.remove("round10");
        document.getElementById("t_round").classList.remove("round11");
        document.getElementById("t_round").classList.remove("round12");
        document.getElementById("t_round").classList.remove("round13");
        document.getElementById("t_round").classList.remove("round14");
        document.getElementById("t_round").classList.remove("round32");
        document.getElementById("t_round").classList.remove("round16");
        document.getElementById("t_round").classList.remove("roundqf");
        document.getElementById("t_round").classList.add("roundsf");
        document.getElementById("t_round").classList.remove("roundgf");
    } else if (round_rep.value == "Grand Finals" ){
        document.getElementById("t_round").classList.remove("round1");
        document.getElementById("t_round").classList.remove("round2");
        document.getElementById("t_round").classList.remove("round3");
        document.getElementById("t_round").classList.remove("round4");
        document.getElementById("t_round").classList.remove("round5");
        document.getElementById("t_round").classList.remove("round6");
        document.getElementById("t_round").classList.remove("round7");
        document.getElementById("t_round").classList.remove("round8");
        document.getElementById("t_round").classList.remove("round9");
        document.getElementById("t_round").classList.remove("round10");
        document.getElementById("t_round").classList.remove("round11");
        document.getElementById("t_round").classList.remove("round12");
        document.getElementById("t_round").classList.remove("round13");
        document.getElementById("t_round").classList.remove("round14");
        document.getElementById("t_round").classList.remove("round32");
        document.getElementById("t_round").classList.remove("round16");
        document.getElementById("t_round").classList.remove("roundqf");
        document.getElementById("t_round").classList.remove("roundsf");
        document.getElementById("t_round").classList.add("roundgf");
    } else {
        document.getElementById("t_round").classList.remove("round1");
        document.getElementById("t_round").classList.remove("round2");
        document.getElementById("t_round").classList.remove("round3");
        document.getElementById("t_round").classList.remove("round4");
        document.getElementById("t_round").classList.remove("round5");
        document.getElementById("t_round").classList.remove("round6");
        document.getElementById("t_round").classList.remove("round7");
        document.getElementById("t_round").classList.remove("round8");
        document.getElementById("t_round").classList.remove("round9");
        document.getElementById("t_round").classList.remove("round10");
        document.getElementById("t_round").classList.remove("round11");
        document.getElementById("t_round").classList.remove("round12");
        document.getElementById("t_round").classList.remove("round13");
        document.getElementById("t_round").classList.remove("round14");
        document.getElementById("t_round").classList.remove("round32");
        document.getElementById("t_round").classList.remove("round16");
        document.getElementById("t_round").classList.remove("roundqf");
        document.getElementById("t_round").classList.remove("roundsf");
        document.getElementById("t_round").classList.remove("roundgf");
    }
});	
p2_name_rep.on('change', (newValue, oldValue) => {	
	p2_name.innerText = `${newValue}` ;
});	
p2_record_rep.on('change', (newValue, oldValue) => {	
	p2_record.innerText = `${newValue}` ;
});	
p2_wins_rep.on('change', (newValue, oldValue) => {	
	if (p2_wins_rep.value == 0){
        document.getElementById("p2_wins").classList.add("score0");
        document.getElementById("p2_wins").classList.remove("score1");
        document.getElementById("p2_wins").classList.remove("score2");
    } else if (p2_wins_rep.value == 1 ){
        document.getElementById("p2_wins").classList.remove("score0");
        document.getElementById("p2_wins").classList.add("score1");
        document.getElementById("p2_wins").classList.remove("score2");
    } else if (p2_wins_rep.value == 2) {
        document.getElementById("p2_wins").classList.remove("score0");
        document.getElementById("p2_wins").classList.remove("score1");
        document.getElementById("p2_wins").classList.add("score2");
    } else {
        document.getElementById("p2_wins").classList.remove("score0");
        document.getElementById("p2_wins").classList.remove("score1");
        document.getElementById("p2_wins").classList.add("score2");
    }
});	